# Generated by Django 6.1 on 2026-09-01 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='emergency',
            new_name='emergency_type',
        ),
        migrations.RenameField(
            model_name='alert',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
