# Generated by Django 6.1 on 2026-09-03 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0002_rename_emergency_alert_emergency_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='helper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alert',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='emergency_type',
            field=models.CharField(choices=[('ACCIDENT', 'Accident'), ('MEDICAL', 'Medical'), ('FIRE', 'Fire'), ('POLICE', 'Police'), ('OTHER', 'Other')], default='Other', max_length=15),
        ),
    ]
