# Generated by Django 6.1 on 2026-09-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0003_alert_accepted_at_alert_helper_alert_resolved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='role',
            field=models.CharField(choices=[('VICTIM', 'Victim'), ('HELPER', 'Helper'), ('ADMIN', 'Admin')], default='VICTIM', max_length=10),
        ),
    ]
