# Generated by Django 6.1 on 2026-09-03 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0004_alert_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='helper',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='role',
        ),
    ]
