# Generated by Django 6.1 on 2026-09-05 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0007_alter_alert_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In progress'), ('CANCELLED', 'Cancelled'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=15),
        ),
    ]
